source "http://rubygems.org"
ruby "2.5.5"

gem "nokogiri"
gem "rack", "~> 2.0.1"
# Use Puma as the app server
gem "puma", "~> 3.12"
# gem Httparty when you want to party Hard
gem "httparty"
# gem bunny Rubbitmq client
gem "bunny", ">= 2.14.1"
gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
# elastic search gem
gem "elasticsearch", "~> 6.1"
# For testing use Rspec
gem "rspec"
gem "rspec-expectations"
# postgres R-Db
gem "postgresql"
